apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dv-operator
  namespace: dv-demo
spec:
  channel: beta
  installPlanApproval: Automatic
  name: dv-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
