apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: rdbms-springboot-sqlserver
spec:
  replicas: 1
  env:
  - name: SPRING_DATASOURCE_SAMPLEDB_USERNAME
    value: sa
  - name: SPRING_DATASOURCE_SAMPLEDB_PASSWORD
    value: P@ssw0rd
  - name: SPRING_DATASOURCE_SAMPLEDB_DATABASENAME
    value: sampledb
  - name: SPRING_DATASOURCE_SAMPLEDB_JDBCURL
    value: jdbc:sqlserver://mssql:1433;databaseName=$(SPRING_DATASOURCE_SAMPLEDB_DATABASENAME);InstanceName=tempdb
  build:
    source:
      dependencies:
        -  com.microsoft.sqlserver:mssql-jdbc:8.2.0.jre11
      ddl: |
        CREATE DATABASE customer OPTIONS (ANNOTATION 'Customer VDB');
        USE DATABASE customer;

        CREATE FOREIGN DATA WRAPPER sqlserver;
        CREATE SERVER sampledb TYPE 'NONE' FOREIGN DATA WRAPPER sqlserver;

        CREATE SCHEMA accounts SERVER sampledb;
        CREATE VIRTUAL SCHEMA portfolio;

        SET SCHEMA accounts;
        IMPORT FOREIGN SCHEMA dbo FROM SERVER sampledb INTO accounts OPTIONS("importer.useFullSchemaName" 'false');

        SET SCHEMA portfolio;

        CREATE VIEW CustomerZip(id integer PRIMARY KEY, name string, ssn string, zip string) AS
            SELECT c.ID as id, c.NAME as name, c.SSN as ssn, a.ZIP as zip
            FROM accounts.CUSTOMER c LEFT OUTER JOIN accounts.ADDRESS a
            ON c.ID = a.CUSTOMER_ID;
